CREATE OR REPLACE FUNCTION RAVEN.FN_REPLACE_COB_PATTERN("FILE_PATH" VARCHAR(16777216), "RAVEN_COBID" NUMBER(38,0))
RETURNS VARCHAR(40)
LANGUAGE SQL
AS $$
    SELECT REPLACE( 
			REPLACE( 
				REPLACE(FILE_PATH
						,'|:YYYY:|', SUBSTRING(RAVEN_COBID::VARCHAR,1,4))
				,'|:YYYYMM:|', SUBSTRING(RAVEN_COBID::VARCHAR,1,6)
				)
				,'|:YYYYMMDD:|', RAVEN_COBID::VARCHAR
			) AS FILE_PATH_COB
$$
;
