create or replace view RAVEN.VW_REP_DATE_DIMENSION(
	DATE,
	YEAR,
	QUARTER,
	MONTH_NUM,
	MONTH_NAME,
	MONTH_NAME_YEAR,
	WEEK_NUM,
	DAY_NUM,
	DAY_NAME,
	DAY_OF_WEEK,
	DAY_OF_YEAR
) as
 -- GENERATES A DAY ROW for 730 days
  WITH CTE_DATE_GENERATOR AS (
    SELECT DATEADD(DAY, SEQ4() * -1, CURRENT_DATE) AS DAY_ROW
      FROM TABLE(GENERATOR(ROWCOUNT=>730))  

  )
  SELECT TO_DATE(DAY_ROW) AS DATE 
        ,YEAR(DAY_ROW) AS YEAR
        ,QUARTER(DAY_ROW) AS QUARTER
        ,MONTH(DAY_ROW) AS MONTH_NUM
        ,MONTHNAME(DAY_ROW) AS MONTH_NAME
        ,MONTHNAME(DAY_ROW) || '-' || TO_CHAR(TO_DATE(DAY_ROW),'YY') AS MONTH_NAME_YEAR
        ,WEEKOFYEAR(DAY_ROW) AS WEEK_NUM
        ,DAY(DAY_ROW) AS DAY_NUM
        ,DAYNAME(DAY_ROW) AS DAY_NAME
        ,DAYOFWEEK(DAY_ROW) AS DAY_OF_WEEK
        ,DAYOFYEAR(DAY_ROW) AS DAY_OF_YEAR
    FROM CTE_DATE_GENERATOR
