create or replace view RAVEN.VW_REP_SNOWFLAKE_PIPE_USAGE_HISTORY(
	PIPE_ID,
	PIPE_NAME,
	START_TIME,
	END_TIME,
	CREDITS_USED,
	BYTES_INSERTED,
	FILES_INSERTED,
	START_DATE,
	PIPELINE_OPERATION_HOURS,
	TIME_OF_DAY
) as
SELECT 
  PIPE_ID,
  PIPE_NAME,
  START_TIME,
  END_TIME,
  CREDITS_USED,
  BYTES_INSERTED,
  FILES_INSERTED,
  TO_DATE(START_TIME) AS START_DATE,
  DATEDIFF(HOUR, START_TIME, END_TIME) AS PIPELINE_OPERATION_HOURS,
  HOUR(START_TIME) AS TIME_OF_DAY
FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
