create or replace view RAVEN.VW_REP_SNOWFLAKE_STORAGE_USAGE_MONTHLY_SUMMARY(
	USAGE_MONTH,
	TOTAL_BILLABLE_STORAGE_TB,
	STORAGE_BILLABLE_STORAGE_TB,
	STAGE_BILLABLE_STORAGE_TB,
	FAILSAFE_BILLABLE_STORAGE_TB
) as
SELECT 
    DATE_TRUNC(MONTH, USAGE_DATE) AS USAGE_MONTH
  , AVG(STORAGE_BYTES + STAGE_BYTES + FAILSAFE_BYTES) / POWER(1024, 4) AS TOTAL_BILLABLE_STORAGE_TB
  , AVG(STORAGE_BYTES ) / POWER(1024, 4) AS STORAGE_BILLABLE_STORAGE_TB
  , AVG(STAGE_BYTES ) / POWER(1024, 4) AS STAGE_BILLABLE_STORAGE_TB
  , AVG(FAILSAFE_BYTES ) / POWER(1024, 4) AS FAILSAFE_BILLABLE_STORAGE_TB
FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE
GROUP BY DATE_TRUNC(MONTH, USAGE_DATE)
