create or replace view RAVEN.VW_REP_SNOWFLAKE_WAREHOUSE_METERING_USER_ESTIMATE(
	USER_NAME,
	WAREHOUSE_SIZE,
	WAREHOUSE_ID,
	WAREHOUSE_NAME,
	MONTH_DATE,
	COUNT_EXECUTION,
	ESTIMATED_CREDITS,
	CREDITS_USED_CLOUD_SERVICES
) as
SELECT 
UPPER(USER_NAME) USER_NAME, 
WAREHOUSE_SIZE, 
WAREHOUSE_ID, 
WAREHOUSE_NAME,
DATE_TRUNC(MONTH, START_TIME) MONTH_DATE,
COUNT(*) COUNT_EXECUTION,
SUM(TOTAL_ELAPSED_TIME/1000 * 
						   CASE WAREHOUSE_SIZE
							   WHEN 'X-Small' 	THEN 1/60/60
							   WHEN 'Small'   	THEN 2/60/60
							   WHEN 'Medium'  	THEN 4/60/60
							   WHEN 'Large'   	THEN 8/60/60
							   WHEN 'X-Large' 	THEN 16/60/60
							   WHEN '2X-Large' 	THEN 32/60/60
							   WHEN '3X-Large' 	THEN 64/60/60
							   WHEN '4X-Large' 	THEN 128/60/60
						   ELSE 0
						   END) AS ESTIMATED_CREDITS,
SUM(CREDITS_USED_CLOUD_SERVICES) CREDITS_USED_CLOUD_SERVICES						   
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
GROUP BY UPPER(USER_NAME), WAREHOUSE_SIZE, WAREHOUSE_ID, WAREHOUSE_NAME, DATE_TRUNC(MONTH, START_TIME);
