create or replace view RAVEN.VW_USERS(
	USER_NAME,
	DISPLAY_NAME,
	DEFAULT_ROLE,
	LAST_SUCCESS_LOGIN
) as
SELECT 
	UPPER(LOGIN_NAME)		AS USER_NAME, 
	IFNULL(MAX(DISPLAY_NAME),UPPER(LOGIN_NAME))		AS DISPLAY_NAME, 
	MAX(DEFAULT_ROLE)		AS DEFAULT_ROLE, 
	MAX(LAST_SUCCESS_LOGIN)	AS LAST_SUCCESS_LOGIN
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
GROUP BY UPPER(LOGIN_NAME)
UNION 
SELECT 'SYSTEM' USER_NAME, 'System' DISPLAY_NAME, NULL DEFAULT_ROLE, NULL LAST_SUCCESS_LOGIN
