create or replace view RAVEN.VW_WAREHOUSE(
	WAREHOUSE_ID,
	WAREHOUSE_NAME_ORIGINAL,
	WAREHOUSE_NAME,
	WAREHOUSE_ENVIRONMENT,
	WAREHOUSE_DATABASE,
	WAREHOUSE_SIZE,
	RAPTOR_ENV
) as
SELECT DISTINCT 
WAREHOUSE_ID,
WAREHOUSE_NAME AS WAREHOUSE_NAME_ORIGINAL,
CASE
	WHEN WAREHOUSE_NAME LIKE '%RAPTOR%' AND SPLIT_PART(WAREHOUSE_NAME,'_',-1) = 'WH' THEN WAREHOUSE_NAME || '_XS' 
	WHEN WAREHOUSE_NAME LIKE '%RAVEN%' AND SPLIT_PART(WAREHOUSE_NAME,'_',-1) = 'WH' THEN WAREHOUSE_NAME || '_XS'
	ELSE WAREHOUSE_NAME 
END AS WAREHOUSE_NAME,    
SPLIT_PART(WAREHOUSE_NAME,'_', 1) WAREHOUSE_ENVIRONMENT,
SPLIT_PART(WAREHOUSE_NAME,'_', 2) WAREHOUSE_DATABASE,
CASE IFF(SPLIT_PART(WAREHOUSE_NAME,'_',-1) = 'WH', 'XS',SPLIT_PART(WAREHOUSE_NAME,'_',-1))
   WHEN 'XS' 	THEN 'X-Small'
   WHEN 'S' 	THEN 'Small'
   WHEN 'M' 	THEN 'Medium'
   WHEN 'L' 	THEN 'Large'
   WHEN 'XL' 	THEN 'X-Large'
   WHEN '2XL' 	THEN '2X-Large'
   WHEN '3XL' 	THEN '3X-Large'
   WHEN '4XL' 	THEN '4X-Large'
   ELSE 'Unknow'
   END WAREHOUSE_SIZE,
LEFT(WAREHOUSE_NAME,4) AS Raptor_ENV
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
