MERGE INTO RAVEN.METADATA_CALENDAR AS tgt
USING (
    SELECT DISTINCT
     date(MY_DATE,'YYYY-MM-DD')		        AS MY_DATE
    ,CAST(IS_BANK_HOLIDAY AS BOOLEAN)       AS IS_BANK_HOLIDAY
    ,date(NEXT_BUSINESS_DAY,'YYYY-MM-DD')   AS NEXT_BUSINESS_DAY
    ,CAST(COBID AS INT)                     AS COBID
FROM RAVEN.TEMP_METADATA_SRC_CALENDAR ) AS src
ON (tgt.COBID=src.COBID)
WHEN MATCHED
THEN UPDATE SET
 tgt.MY_DATE=src.MY_DATE
,tgt."YEAR"=YEAR(src.MY_DATE)
,tgt."MONTH"=MONTH(src.MY_DATE)
,tgt.MONTH_NAME=MONTHNAME(src.MY_DATE)
,tgt.DAY_OF_MON=DAY(src.MY_DATE)
,tgt.DAY_WEEK_NAME=DAYNAME(src.MY_DATE) 
,tgt.DAY_OF_WEEK=DAYOFWEEK(src.MY_DATE)
,tgt.WEEK_OF_YEAR=WEEKOFYEAR(src.MY_DATE)
,tgt.DAY_OF_YEAR=DAYOFYEAR(src.MY_DATE)
,tgt.IS_BANK_HOLIDAY=src.IS_BANK_HOLIDAY
,tgt.NEXT_BUSINESS_DAY=src.NEXT_BUSINESS_DAY
,tgt.LAST_MODIFIED=CURRENT_TIMESTAMP()
,tgt.FIRST_TIME_INSERTED=nvl(tgt.FIRST_TIME_INSERTED,CURRENT_TIMESTAMP())
WHEN NOT MATCHED
THEN INSERT (
    COBID, 
MY_DATE, 
"YEAR", 
"MONTH", 
MONTH_NAME, 
DAY_OF_MON, 
DAY_WEEK_NAME, 
DAY_OF_WEEK, 
WEEK_OF_YEAR, 
DAY_OF_YEAR, 
IS_BANK_HOLIDAY, 
NEXT_BUSINESS_DAY, 
LAST_MODIFIED,
FIRST_TIME_INSERTED)
VALUES (
 src.COBID
,src.MY_DATE 
,YEAR(src.MY_DATE)
,MONTH(src.MY_DATE)
,MONTHNAME(src.MY_DATE)
,DAY(src.MY_DATE)
,DAYNAME(src.MY_DATE) 
,DAYOFWEEK(src.MY_DATE)
,WEEKOFYEAR(src.MY_DATE)
,DAYOFYEAR(src.MY_DATE)
,src.IS_BANK_HOLIDAY
,src.NEXT_BUSINESS_DAY
,CURRENT_TIMESTAMP()
,CURRENT_TIMESTAMP()
);
