MERGE INTO RAVEN.METADATA_SOURCE_FIELD AS tgt
USING 
(
	SELECT
		 IFNULL(src.SOURCE_SYSTEM_CODE, tgt.SOURCE_SYSTEM_CODE) SOURCE_SYSTEM_CODE
		,IFNULL(src.SOURCE_FEED_CODE, tgt.SOURCE_FEED_CODE) SOURCE_FEED_CODE
		,IFNULL(TRIM(src.SOURCE_FIELD_NAME), tgt.SOURCE_FIELD_NAME) SOURCE_FIELD_NAME
		,src.TARGET_FIELD_NAME
		,src.FIELD_ORDINAL
		,src.DATA_TYPE_NAME
		,src.DATA_TYPE_LENGTH
		,src.DATA_TYPE_PRECISION
		,src.DATA_TYPE_SCALE
		,src.IS_IN_SOURCE
		,src.IS_IN_TARGET
		,src.IS_DELETED
		,src.DERIVED_EXPRESSION
		,IFF(src.SOURCE_SYSTEM_CODE IS NULL, 'DISABLE', 'UPDATE') AS ACTION_UPDATE
	FROM RAVEN.TEMP_METADATA_SRC_SOURCE_FIELD src
	FULL OUTER JOIN RAVEN.METADATA_SOURCE_FIELD tgt 
		ON src.SOURCE_SYSTEM_CODE = tgt.SOURCE_SYSTEM_CODE 
		AND src.SOURCE_FEED_CODE = tgt.SOURCE_FEED_CODE 
		AND TRIM(src.SOURCE_FIELD_NAME)=tgt.SOURCE_FIELD_NAME
) AS src
ON (
	tgt.SOURCE_SYSTEM_CODE=src.SOURCE_SYSTEM_CODE 
AND tgt.SOURCE_FEED_CODE=src.SOURCE_FEED_CODE 
AND tgt.SOURCE_FIELD_NAME=TRIM(src.SOURCE_FIELD_NAME)
)
WHEN MATCHED AND ACTION_UPDATE = 'UPDATE'
THEN UPDATE SET
tgt.TARGET_FIELD_NAME=src.TARGET_FIELD_NAME, 
tgt.FIELD_ORDINAL=src.FIELD_ORDINAL, 
tgt.DATA_TYPE_NAME=src.DATA_TYPE_NAME, 
tgt.DATA_TYPE_LENGTH=src.DATA_TYPE_LENGTH, 
tgt.DATA_TYPE_PRECISION=src.DATA_TYPE_PRECISION, 
tgt.DATA_TYPE_SCALE=src.DATA_TYPE_SCALE, 
tgt.IS_IN_SOURCE=src.IS_IN_SOURCE, 
tgt.IS_IN_TARGET=src.IS_IN_TARGET, 
tgt.IS_DELETED=src.IS_DELETED, 
tgt.DERIVED_EXPRESSION=src.DERIVED_EXPRESSION,
tgt.LAST_MODIFIED=CURRENT_TIMESTAMP(),
tgt.FIRST_TIME_INSERTED=nvl(tgt.FIRST_TIME_INSERTED,CURRENT_TIMESTAMP())
WHEN MATCHED AND ACTION_UPDATE = 'DISABLE'
THEN DELETE
WHEN NOT MATCHED
THEN INSERT (
SOURCE_SYSTEM_CODE, 
SOURCE_FEED_CODE, 
SOURCE_FIELD_NAME, 
TARGET_FIELD_NAME, 
FIELD_ORDINAL, 
DATA_TYPE_NAME, 
DATA_TYPE_LENGTH, 
DATA_TYPE_PRECISION, 
DATA_TYPE_SCALE, 
IS_IN_SOURCE, 
IS_IN_TARGET, 
IS_DELETED, 
DERIVED_EXPRESSION,
LAST_MODIFIED,
FIRST_TIME_INSERTED)
VALUES (
src.SOURCE_SYSTEM_CODE, 
src.SOURCE_FEED_CODE, 
TRIM(src.SOURCE_FIELD_NAME), 
src.TARGET_FIELD_NAME, 
src.FIELD_ORDINAL, 
src.DATA_TYPE_NAME, 
src.DATA_TYPE_LENGTH, 
src.DATA_TYPE_PRECISION, 
src.DATA_TYPE_SCALE,
src.IS_IN_SOURCE, 
src.IS_IN_TARGET, 
src.IS_DELETED, 
src.DERIVED_EXPRESSION,
CURRENT_TIMESTAMP(),
CURRENT_TIMESTAMP())
;
