CREATE or replace TABLE RAVEN.LOG_FILE_OUTLIER_BOUNDS (
    DATASET_NAME VARCHAR(5000) COLLATE 'UTF8',
    Q_THREE NUMBER(38,6),
    Q_ONE NUMBER(38,6),
    OUTLIER_RANGE NUMBER(38,6),
    LOWER_BOUND NUMBER(38,6),
    UPPER_BOUND NUMBER(38,6),
    BOUNDS VARCHAR(5000),
	constraint PK_LOG_FILE_OUTLIER_BOUNDS primary key (DATASET_NAME)
)
;
