CREATE or replace TABLE RAVEN.LOG_STAGE_ME_STATUS (
	ID NUMBER(38,0) NOT NULL,
	RAVEN_COBID NUMBER(38,0) NOT NULL,
	DATASET_NAME VARCHAR(5000) COLLATE 'UTF8',
	PROCESS_PARAMETERS VARIANT,
	PROCESS_RESULT VARIANT,
	PROCESS_STATUS VARCHAR(500),
	START_TIMESTAMP TIMESTAMP_TZ(9),
	END_TIMESTAMP TIMESTAMP_TZ(9),
	BLOB_FILE VARIANT,
	constraint PK_LOG_STAGE_ME_STATUS primary key (ID)
)
;
