CREATE or replace TABLE RAVEN.METADATA_CALENDAR (
	COBID NUMBER(38,0) NOT NULL,
	MY_DATE DATE NOT NULL,
	YEAR NUMBER(38,0) NOT NULL,
	MONTH NUMBER(38,0) NOT NULL,
	MONTH_NAME VARCHAR(3) NOT NULL COLLATE 'en-ci',
	DAY_OF_MON NUMBER(38,0) NOT NULL,
	DAY_WEEK_NAME VARCHAR(3) NOT NULL COLLATE 'en-ci',
	DAY_OF_WEEK VARCHAR(9) NOT NULL COLLATE 'en-ci',
	WEEK_OF_YEAR NUMBER(38,0) NOT NULL,
	DAY_OF_YEAR NUMBER(38,0) NOT NULL,
	IS_BANK_HOLIDAY BOOLEAN DEFAULT FALSE,
	NEXT_BUSINESS_DAY DATE,
	FIRST_TIME_INSERTED TIMESTAMP_TZ(9),
	LAST_MODIFIED TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_METADATA_CALENDAR primary key (COBID)
)
;
