CREATE or replace TABLE RAVEN.METADATA_SOURCE_FILE (
	SOURCE_SYSTEM_CODE VARCHAR(200) NOT NULL,
	SOURCE_FEED_CODE VARCHAR(200) NOT NULL,
	STAGE_NAME VARCHAR(500),
	SOURCE_FILE_PATH VARCHAR(500),
	SOURCE_FILE_NAME_PATTERN VARCHAR(500),
	DESTINATION_SCHEMA_NAME VARCHAR(250) NOT NULL,
	DESTINATION_TABLE_NAME VARCHAR(250) NOT NULL,
	IS_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
	FILE_FORMAT VARCHAR(200) NOT NULL,
	DATE_INPUT_FORMAT VARCHAR(200) NOT NULL DEFAULT 'DD/MM/YYYY',
	TIMESTAMP_INPUT_FORMAT VARCHAR(200) NOT NULL DEFAULT 'DD/MM/YYYY HH24:MI:SS.FF3',
	SKIP_ROW_ON_ERROR NUMBER(38,0) NOT NULL DEFAULT 0,
	DELETE_STAGE_BY_FILE_NAME BOOLEAN NOT NULL DEFAULT FALSE,
	TIMEZONE VARCHAR(200),
	FIRST_TIME_INSERTED TIMESTAMP_TZ(9),
	LAST_MODIFIED TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_METADATA_SOURCE_FILE primary key (SOURCE_SYSTEM_CODE, SOURCE_FEED_CODE)
)
;
