CREATE or replace TASK RAVEN.TASK_UPDATE_OUTLIER_BOUNDS
    USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    SCHEDULE = 'USING CRON 0 2 * * * UTC'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    SUSPEND_TASK_AFTER_NUM_FAILURES = 15
AS
    MERGE INTO RAVEN.LOG_FILE_OUTLIER_BOUNDS AS tgt
    USING RAVEN.VW_LOG_FILE_OUTLIER_BOUNDS AS src
    ON (tgt.DATASET_NAME=src.DATASET_NAME)
    WHEN MATCHED
    THEN UPDATE SET
        tgt.Q_THREE=src.Q_THREE, 
        tgt.Q_ONE=src.Q_ONE, 
        tgt.OUTLIER_RANGE=src.OUTLIER_RANGE, 
        tgt.LOWER_BOUND=src.LOWER_BOUND, 
        tgt.UPPER_BOUND=src.UPPER_BOUND, 
        tgt.BOUNDS=src.BOUNDS
    WHEN NOT MATCHED
    THEN INSERT (
        DATASET_NAME, 
        Q_THREE, Q_ONE, 
        OUTLIER_RANGE, 
        LOWER_BOUND, 
        UPPER_BOUND, 
        BOUNDS
    ) VALUES (
        src.DATASET_NAME, 
        src.Q_THREE, 
        src.Q_ONE, 
        src.OUTLIER_RANGE, 
        src.LOWER_BOUND, 
        src.UPPER_BOUND, 
        src.BOUNDS)
;
