CREATE or replace TASK RAVEN.TASK_RETRY_UNSTAGED_FILES
    WAREHOUSE = 'DEMO_WH'
    AFTER RAVEN.TASK_LIST_STORAGE_SPACES
AS
DECLARE
  COBID_START INTEGER;
  COBID_END   INTEGER;
  res RESULTSET DEFAULT 
  (
    SELECT 
      MIN(RAVEN_COBID) COBID_START, 
      MAX(RAVEN_COBID) COBID_END 
      FROM (SELECT 
              DISTINCT RAVEN_COBID 
              FROM RAVEN.LOG_LIST_EXTERNAL_FILE 
             WHERE FLAG_LAST_VERSION = TRUE 
             ORDER BY RAVEN_COBID DESC LIMIT 5
          )
  );
  c1 CURSOR FOR res;
BEGIN
  FOR row_variable IN c1 DO
  	COBID_START := row_variable.COBID_START;
    COBID_END := row_variable.COBID_END;
    CALL RAVEN.RETRY_UNSTAGED_FILES(:COBID_START,:COBID_END);
  END FOR;
END;
